---
- name: In-Memory inventory playbook
  hosts: workstation
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
      register: result

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.openstack_servers}}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.openstack_servers}}"

- name : setup for all server
  hosts: all
  become: true
  roles: 
    - {name: common}

- name : setup for db-tier
  hosts: appdb1 
  become: true
  roles:
    - {name: db-tier}

- name : setup for app-tier
  hosts: apps
  become: true
  roles:
    - {name: app-tier}

- name : setup for frontend-tier
  hosts: frontends
  become: true
  roles:
    - {name: frontend-tier}

- name : smoke-test
  hosts: localhost
  become: false
  roles:
    - {name: smoke-test}
