---
# tasks file for frontend-tier
- name: http
  package:
    name: httpie
    state: latest

- name: install {{ package_name }}
  yum:
    name: "{{ package_name }}"
    state: latest

- name: enable {{ package_name }}
  service:
    name: "{{ package_name }}"
    enabled: yes

- name: configure {{ package_name }}
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: restart {{ package_name }}
  service:
    name: "{{ package_name }}"
    state: restarted
