---
# tasks file for db-tier
- name: install {{ package_name }}
  package:
    name: "{{ package_name }}"
    state: latest

- name: enable {{ package_name }} at boot
  service:
    name: "{{ service_name }}"
    enabled: yes
      
#- name: tell user to finish setting up postgres
#  debug:
#    msg: "Either uncomment the postgres setup or manually login and initialize"

# only run the next 2 tasks once!
#- name: initilize postgres
#  command: postgresql-setup initdb
#
#- name: initilize postgres some more
#  command: chkconfig postgresql on

- name: start {{ package_name }}
  service:
    name: "{{ service_name }}"
    state: started