---
# tasks file for app-tier
- name: install {{ package_name }}
  package:
    name: "{{ package_name }}"
    state: latest
    
- name: enable {{ package_name }} at boot
  service:
    name: "{{ package_name }}"
    enabled: yes

- name: create tomcat webroot directory
  file:
    path: "{{ webroot_dir }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ webroot_dir }}/index.html"
    mode: 0644

- name: restart {{ package_name }}
  service:
    name: "{{ package_name }}"
    state: restarted
